"""Grafana environment variable names."""

from __future__ import annotations

GRAFANA_INSTANCE_URL_ENV = "GRAFANA_INSTANCE_URL"
GRAFANA_READ_TOKEN_ENV = "GRAFANA_READ_TOKEN"
GRAFANA_VERIFY_SSL_ENV = "GRAFANA_VERIFY_SSL"
GRAFANA_CA_BUNDLE_ENV = "GRAFANA_CA_BUNDLE"
GRAFANA_LOKI_DATASOURCE_UID_ENV = "GRAFANA_LOKI_DATASOURCE_UID"
GRAFANA_TEMPO_DATASOURCE_UID_ENV = "GRAFANA_TEMPO_DATASOURCE_UID"
GRAFANA_MIMIR_DATASOURCE_UID_ENV = "GRAFANA_MIMIR_DATASOURCE_UID"

#: Comma-separated Mimir UIDs, tried in order. A Grafana instance can front
#: several Prometheus servers whose metric coverage does not overlap.
GRAFANA_MIMIR_DATASOURCE_UIDS_ENV = "GRAFANA_MIMIR_DATASOURCE_UIDS"

__all__ = [
    "GRAFANA_CA_BUNDLE_ENV",
    "GRAFANA_INSTANCE_URL_ENV",
    "GRAFANA_LOKI_DATASOURCE_UID_ENV",
    "GRAFANA_MIMIR_DATASOURCE_UIDS_ENV",
    "GRAFANA_MIMIR_DATASOURCE_UID_ENV",
    "GRAFANA_READ_TOKEN_ENV",
    "GRAFANA_TEMPO_DATASOURCE_UID_ENV",
    "GRAFANA_VERIFY_SSL_ENV",
]
